#!/usr/bin/env python3
"""
generate_report.py

Reads the combined_report.json generated by analyze_samples_rsfiles.py
and produces a statistical summary and a bar chart visualization comparing
the prompting strategies using raw success counts instead of percentages.
"""

import json
import argparse
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def main():
    parser = argparse.ArgumentParser(description="Generate statistics and visualization from report JSON.")
    parser.add_argument("--input", default="output/grok/combined_report.json", help="Path to combined_report.json")
    parser.add_argument("--output-img", default="output/grok/grok_performance_chart.png", help="Path to save the chart")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: {input_path} not found. Please check the path.")
        return

    # 1. Load the Data
    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # 2. Extract Metrics
    records = []
    for file_data in data.get('files', []):
        source = file_data.get('source_file', '')
        
        # Determine strategy based on folder name
        if 'zeroShot' in source:
            strategy = 'Zero-Shot'
        elif 'chainThought' in source:
            strategy = 'Chain-of-Thought'
        elif 'constraintBased' in source:
            strategy = 'Constraint-Based'
        else:
            strategy = 'Unknown'

        # Extract success booleans
        records.append({
            'File': source,
            'Strategy': strategy,
            'Station 1: Raw Compile (rustc)': file_data.get('rustc_compile', {}).get('ok', False),
            'Station 2: Project Compile (cargo check)': file_data.get('cargo_check', {}).get('ok', False),
            'Station 2: Idiomatic/Quality (cargo clippy)': file_data.get('clippy', {}).get('ok', False)
        })

    df = pd.DataFrame(records)

    # 3. Calculate Counts (Instead of Percentages)
    # We use pandas aggregation to count total rows (size) and count True values (sum)
    summary_df = df.groupby('Strategy').agg(
        **{
            'Total Samples': ('File', 'size'),
            'Station 1: Raw Compile (rustc)': ('Station 1: Raw Compile (rustc)', 'sum'),
            'Station 2: Project Compile (cargo check)': ('Station 2: Project Compile (cargo check)', 'sum'),
            'Station 2: Idiomatic/Quality (cargo clippy)': ('Station 2: Idiomatic/Quality (cargo clippy)', 'sum')
        }
    )
    
    print("\n" + "="*85)
    print(" 📊 GROK PERFORMANCE REPORT BY PROMPT STRATEGY (RAW COUNTS)")
    print("="*85)
    print(summary_df.to_string())
    print("="*85 + "\n")

    # 4. Generate Visualization
    # Drop 'Total Samples' from the plot so we only graph the success metrics
    plot_df = summary_df.drop(columns=['Total Samples']).reset_index()
    
    # Melt the dataframe for Seaborn to easily plot grouped bars
    melted_df = plot_df.melt(
        id_vars='Strategy', 
        var_name='Metric', 
        value_name='Success Count'
    )

    # Set up the plot style
    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(11, 6))

    # Create a grouped bar chart
    ax = sns.barplot(
        data=melted_df, 
        x='Strategy', 
        y='Success Count', 
        hue='Metric',
        palette="viridis"
    )

    # Formatting the chart for the paper
    plt.title('Grok Code Generation Performance by Prompting Strategy\n(CVE-2025-68260 Mitigation Task)', fontsize=14, pad=15)
    plt.ylabel('Number of Successful Samples', fontsize=12)
    plt.xlabel('Prompting Strategy', fontsize=12)
    
    # Dynamically set Y-axis limit based on total samples (e.g., 10 + 2 for headroom)
    max_samples = summary_df['Total Samples'].max()
    plt.ylim(0, max_samples + 2) 
    
    plt.legend(title='Evaluation Metric', loc='upper right')

    # Add exact count labels on top of the bars
    for p in ax.patches:
        height = p.get_height()
        # Only annotate if the value is not NaN
        if pd.notnull(height):
            ax.annotate(f'{int(height)}', 
                        (p.get_x() + p.get_width() / 2., height), 
                        ha='center', va='bottom', 
                        fontsize=10, color='black', xytext=(0, 2), 
                        textcoords='offset points')

    # Save the plot
    plt.tight_layout()
    plt.savefig(args.output_img, dpi=300)
    print(f"✅ Visualization saved successfully to: {args.output_img}")

if __name__ == "__main__":
    main()